Replaced many strings with constants
ECE452-S22/project pull request #14
Opened 2022-07-04 21:52 UTC by danielkim10

As the project grows and more prefabs are created, it will be helpful to rely on constants instead of raw strings.

Applied this to all scenes, sprites, objects, prefabs, tags, player pref keys, buttons, overlays

Did not apply this to: ingame strings

That will be for another PR...

2022-07-04 22:06 UTC, kcchik requested changes
nice

2022-07-04 22:06 UTC, kcchik commented on Assets/Constants/Constants.cs
> +}
add newline

2022-07-04 22:11 UTC, danielkim10 commented on Assets/Constants/Constants.cs
> +}
i hate you

2022-07-04 22:12 UTC, Agam642 approved these changes
Looks good just some string changes

2022-07-04 22:14 UTC, gerathas reviewed
Looks good

2022-07-04 22:15 UTC, gerathas approved these changes

2022-07-04 23:19 UTC, Raymond-Xia approved these changes
Looks swag, this guy actually has good code practices kekw

2022-07-05 00:05 UTC, kcchik requested changes

2022-07-05 00:05 UTC, kcchik commented on Assets/Constants/Constants.cs
> +}
looks like its still missing a newline

2022-07-05 00:07 UTC, kcchik commented on Assets/Constants/Constants.cs
> +}
mb

2022-07-05 06:03 UTC, kcchik approved these changes

2022-07-05 06:04 UTC, merged