skins
ECE452-S22/project pull request #57
Opened 2022-07-19 23:37 UTC by kcchik

skins

2022-07-19 23:45 UTC, danielkim10 requested changes
Getting an IndexOutOfBoundsException while scrolling through skins in shop.

2022-07-20 00:07 UTC, Raymond-Xia commented
> Getting an IndexOutOfBoundsException while scrolling through skins in shop.

![image](https://user-images.githubusercontent.com/32081318/179868413-a034b510-45dc-45c6-974b-42b1b186cfef.png)
Still getting it

2022-07-20 00:12 UTC, Raymond-Xia requested changes
Da top hats aren't white outlined !

2022-07-20 00:16 UTC, danielkim10 approved these changes

2022-07-20 00:16 UTC, Raymond-Xia approved these changes

2022-07-20 00:22 UTC, merged